### PR TITLE
Django 1.7 migrations

### PR DESCRIPTION
**Pull request by emord**
Going to test this on staging first.

cc: @gcapalbo

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 15 errors:

* touchforms/formplayer/south_migrations/0001_initial.py, line 5 - F401 'models' imported but unused
* touchforms/formplayer/south_migrations/0001_initial.py, line 7 - E302 expected 2 blank lines, found 1
* touchforms/formplayer/south_migrations/0001_initial.py, line 10 - W293 blank line contains whitespace
* touchforms/formplayer/south_migrations/0001_initial.py, line 36 - E303 too many blank lines (2)
* touchforms/formplayer/south_migrations/0001_initial.py, line 37 - W293 blank line contains whitespace
* touchforms/formplayer/south_migrations/0001_initial.py, line 45 - E303 too many blank lines (2)
* touchforms/formplayer/south_migrations/0001_initial.py, line 45 - F811 redefinition of unused 'models' from line 5
* touchforms/formplayer/south_migrations/0001_initial.py, line 50 - E501 line too long (158 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 53 - E501 line too long (187 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 55 - E501 line too long (123 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 61 - E501 line too long (140 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 64 - E501 line too long (149 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 69 - E501 line too long (139 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 72 - E501 line too long (164 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 76 - E501 line too long (161 > 115 characters)

**Comment by dimagimon** [comment]
There are 15 errors:

* touchforms/formplayer/south_migrations/0001_initial.py, line 5 - F401 'models' imported but unused
* touchforms/formplayer/south_migrations/0001_initial.py, line 7 - E302 expected 2 blank lines, found 1
* touchforms/formplayer/south_migrations/0001_initial.py, line 10 - W293 blank line contains whitespace
* touchforms/formplayer/south_migrations/0001_initial.py, line 36 - E303 too many blank lines (2)
* touchforms/formplayer/south_migrations/0001_initial.py, line 37 - W293 blank line contains whitespace
* touchforms/formplayer/south_migrations/0001_initial.py, line 45 - E303 too many blank lines (2)
* touchforms/formplayer/south_migrations/0001_initial.py, line 45 - F811 redefinition of unused 'models' from line 5
* touchforms/formplayer/south_migrations/0001_initial.py, line 50 - E501 line too long (158 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 53 - E501 line too long (187 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 55 - E501 line too long (123 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 61 - E501 line too long (140 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 64 - E501 line too long (149 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 69 - E501 line too long (139 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 72 - E501 line too long (164 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 76 - E501 line too long (161 > 115 characters)

**Comment by emord** [comment]
Deployed to staging and migrations did not freak out.

**Comment by gcapalbo** [comment]
(same comments here as https://github.com/dimagi/pillowtop/pull/120#issuecomment-123111465)

cc'ing @czue and @snopoke in case they also want to have a look

**Comment by gcapalbo** [comment]
:+1:

**Comment by gcapalbo** [comment]
(I think the merge is still pending @czue's comment about thinking through what else might go wrong and coming up with a rollout plan: https://github.com/dimagi/pillowtop/pull/120#issuecomment-123203411)

**Comment by dimagimon** [comment]
There are 15 errors:

* touchforms/formplayer/south_migrations/0001_initial.py, line 5 - F401 'models' imported but unused
* touchforms/formplayer/south_migrations/0001_initial.py, line 7 - E302 expected 2 blank lines, found 1
* touchforms/formplayer/south_migrations/0001_initial.py, line 10 - W293 blank line contains whitespace
* touchforms/formplayer/south_migrations/0001_initial.py, line 36 - E303 too many blank lines (2)
* touchforms/formplayer/south_migrations/0001_initial.py, line 37 - W293 blank line contains whitespace
* touchforms/formplayer/south_migrations/0001_initial.py, line 45 - E303 too many blank lines (2)
* touchforms/formplayer/south_migrations/0001_initial.py, line 45 - F811 redefinition of unused 'models' from line 5
* touchforms/formplayer/south_migrations/0001_initial.py, line 50 - E501 line too long (158 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 53 - E501 line too long (187 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 55 - E501 line too long (123 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 61 - E501 line too long (140 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 64 - E501 line too long (149 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 69 - E501 line too long (139 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 72 - E501 line too long (164 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 76 - E501 line too long (161 > 115 characters)

**Comment by dimagimon** [comment]
There are 15 errors:

* touchforms/formplayer/south_migrations/0001_initial.py, line 5 - F401 'models' imported but unused
* touchforms/formplayer/south_migrations/0001_initial.py, line 7 - E302 expected 2 blank lines, found 1
* touchforms/formplayer/south_migrations/0001_initial.py, line 10 - W293 blank line contains whitespace
* touchforms/formplayer/south_migrations/0001_initial.py, line 36 - E303 too many blank lines (2)
* touchforms/formplayer/south_migrations/0001_initial.py, line 37 - W293 blank line contains whitespace
* touchforms/formplayer/south_migrations/0001_initial.py, line 45 - E303 too many blank lines (2)
* touchforms/formplayer/south_migrations/0001_initial.py, line 45 - F811 redefinition of unused 'models' from line 5
* touchforms/formplayer/south_migrations/0001_initial.py, line 50 - E501 line too long (158 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 53 - E501 line too long (187 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 55 - E501 line too long (123 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 61 - E501 line too long (140 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 64 - E501 line too long (149 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 69 - E501 line too long (139 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 72 - E501 line too long (164 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 76 - E501 line too long (161 > 115 characters)

**Comment by dimagimon** [comment]
There are 15 errors:

* touchforms/formplayer/south_migrations/0001_initial.py, line 5 - F401 'models' imported but unused
* touchforms/formplayer/south_migrations/0001_initial.py, line 7 - E302 expected 2 blank lines, found 1
* touchforms/formplayer/south_migrations/0001_initial.py, line 10 - W293 blank line contains whitespace
* touchforms/formplayer/south_migrations/0001_initial.py, line 36 - E303 too many blank lines (2)
* touchforms/formplayer/south_migrations/0001_initial.py, line 37 - W293 blank line contains whitespace
* touchforms/formplayer/south_migrations/0001_initial.py, line 45 - E303 too many blank lines (2)
* touchforms/formplayer/south_migrations/0001_initial.py, line 45 - F811 redefinition of unused 'models' from line 5
* touchforms/formplayer/south_migrations/0001_initial.py, line 50 - E501 line too long (158 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 53 - E501 line too long (187 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 55 - E501 line too long (123 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 61 - E501 line too long (140 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 64 - E501 line too long (149 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 69 - E501 line too long (139 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 72 - E501 line too long (164 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 76 - E501 line too long (161 > 115 characters)

**Comment by dimagimon** [comment]
There are 15 errors:

* touchforms/formplayer/south_migrations/0001_initial.py, line 5 - F401 'models' imported but unused
* touchforms/formplayer/south_migrations/0001_initial.py, line 7 - E302 expected 2 blank lines, found 1
* touchforms/formplayer/south_migrations/0001_initial.py, line 10 - W293 blank line contains whitespace
* touchforms/formplayer/south_migrations/0001_initial.py, line 36 - E303 too many blank lines (2)
* touchforms/formplayer/south_migrations/0001_initial.py, line 37 - W293 blank line contains whitespace
* touchforms/formplayer/south_migrations/0001_initial.py, line 45 - E303 too many blank lines (2)
* touchforms/formplayer/south_migrations/0001_initial.py, line 45 - F811 redefinition of unused 'models' from line 5
* touchforms/formplayer/south_migrations/0001_initial.py, line 50 - E501 line too long (158 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 53 - E501 line too long (187 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 55 - E501 line too long (123 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 61 - E501 line too long (140 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 64 - E501 line too long (149 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 69 - E501 line too long (139 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 72 - E501 line too long (164 > 115 characters)
* touchforms/formplayer/south_migrations/0001_initial.py, line 76 - E501 line too long (161 > 115 characters)

**Comment by emord** [comment]
@dannyroberts These tests don't depend on django. Also been running on staging for 2 weeks. Should be good to go.

**Comment by czue** [comment]
is staging running 1.7 or 1.6 right now? assuming this should work on either version?

**Comment by emord** [comment]
@czue works on django 1.7 or south 1.0

**Comment by benrudolph** [comment]
:tada: :tada: :tada:

**Comment by czue** [comment]
:boom:
